# Generated by Django 4.2.24 on 2025-09-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='demo_type',
            field=models.CharField(blank=True, choices=[('WATCH', 'Watch Stage'), ('TRY', 'Try Stage')], help_text='Type of demo stage this video is used for', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='demo_violations',
            field=models.JSONField(default=list, help_text='Demo violation data with bbox coordinates and metadata'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Whether this is a demo video'),
        ),
    ]
