# Generated by Django 4.2.24 on 2025-09-24 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_ai_analysis_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_team_invite_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_video_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_trial_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_conversion_score',
            field=models.IntegerField(default=0, help_text='Predictive score for trial to paid conversion'),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_reports_downloaded',
            field=models.IntegerField(default=0, help_text='Number of reports downloaded in trial'),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_stores_used',
            field=models.IntegerField(default=0, help_text='Number of stores created in trial'),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_videos_used',
            field=models.IntegerField(default=0, help_text='Number of videos uploaded in trial'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('GM', 'General Manager'), ('INSPECTOR', 'Inspector'), ('TRIAL_ADMIN', 'Trial Admin')], default='INSPECTOR', max_length=20),
        ),
    ]
