# Generated by Django 4.2.24 on 2025-09-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_at_user_first_ai_analysis_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='demo_completed_at',
            field=models.DateTimeField(blank=True, help_text='When user completed the demo', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_seen_demo',
            field=models.BooleanField(default=False, help_text='Whether user has viewed the interactive demo'),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_demo',
            field=models.BooleanField(default=False, help_text='User explicitly requested to see demo'),
        ),
    ]
