# Generated by Django 4.2.24 on 2025-09-24 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_demo_completed_at_user_has_seen_demo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DEMO_STARTED', 'Demo Started'), ('DEMO_COMPLETED', 'Demo Completed'), ('DEMO_SKIPPED', 'Demo Skipped'), ('UPLOAD_INITIATED', 'Upload Initiated'), ('UPLOAD_COMPLETED', 'Upload Completed'), ('UPLOAD_FAILED', 'Upload Failed'), ('LOGIN', 'User Login'), ('DASHBOARD_VIEW', 'Dashboard Viewed'), ('VIDEO_VIEW', 'Video Viewed'), ('INSPECTION_VIEW', 'Inspection Viewed'), ('TRIAL_EXTENDED', 'Trial Extended'), ('UPGRADE_CLICKED', 'Upgrade Button Clicked'), ('BILLING_VIEW', 'Billing Page Viewed'), ('INACTIVITY_7_DAYS', '7 Days Inactive'), ('TRIAL_EXPIRY_WARNING', 'Trial Expiry Warning Shown'), ('SESSION_TIMEOUT', 'Session Timed Out')], max_length=50)),
                ('metadata', models.JSONField(default=dict, help_text='Additional event context and data')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, help_text='Browser session identifier', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_behavior_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='user_behavi_user_id_a5d31d_idx'), models.Index(fields=['user', 'timestamp'], name='user_behavi_user_id_159754_idx'), models.Index(fields=['event_type', 'timestamp'], name='user_behavi_event_t_cc7fbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmartNudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nudge_type', models.CharField(choices=[('UPLOAD_FIRST_VIDEO', 'Upload Your First Video'), ('COMPLETE_DEMO', 'Complete the Demo'), ('EXPLORE_FEATURES', 'Explore More Features'), ('RETURN_AFTER_UPLOAD', 'Check Your Analysis Results'), ('TRY_SECOND_VIDEO', 'Upload Another Video'), ('VIEW_DETAILED_REPORT', 'View Detailed Report'), ('TRIAL_EXPIRING_SOON', 'Trial Expiring Soon'), ('UPGRADE_PROMPT', 'Upgrade to Continue'), ('FEATURE_LIMIT_REACHED', 'Feature Limit Reached'), ('INACTIVE_USER', 'We Miss You'), ('UNFINISHED_UPLOAD', 'Complete Your Upload')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('cta_text', models.CharField(blank=True, help_text='Call to action button text', max_length=100)),
                ('cta_url', models.CharField(blank=True, help_text='Call to action URL', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHOWN', 'Shown'), ('CLICKED', 'Clicked'), ('DISMISSED', 'Dismissed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('priority', models.IntegerField(default=1, help_text='1=highest, 5=lowest priority')),
                ('trigger_condition', models.JSONField(default=dict, help_text='Conditions that triggered this nudge')),
                ('show_after', models.DateTimeField(help_text='Earliest time to show this nudge')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this nudge expires', null=True)),
                ('shown_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'smart_nudges',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='smart_nudge_user_id_416653_idx'), models.Index(fields=['user', 'show_after'], name='smart_nudge_user_id_200938_idx'), models.Index(fields=['nudge_type', 'status'], name='smart_nudge_nudge_t_b89970_idx')],
            },
        ),
    ]
