# Generated by Django 4.2.23 on 2025-10-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userbehaviorevent_smartnudge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('GM', 'General Manager'), ('INSPECTOR', 'Inspector'), ('TRIAL_ADMIN', 'Trial Admin')], default='INSPECTOR', max_length=20),
        ),
    ]
