# Generated by Django 4.2.24 on 2025-10-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_upload_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='mode',
            field=models.CharField(choices=[('enterprise', 'Enterprise Mode'), ('coaching', 'Coaching Mode')], max_length=20),
        ),
    ]
