# Generated by Django 4.2.24 on 2025-10-02 19:28

from django.db import migrations


def rename_upload_mode(apps, schema_editor):
    """Rename 'inspection' mode to 'enterprise' in existing data"""
    Upload = apps.get_model('uploads', 'Upload')
    Upload.objects.filter(mode='inspection').update(mode='enterprise')


def reverse_rename_upload_mode(apps, schema_editor):
    """Reverse: rename 'enterprise' back to 'inspection'"""
    Upload = apps.get_model('uploads', 'Upload')
    Upload.objects.filter(mode='enterprise').update(mode='inspection')


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_upload_mode'),
    ]

    operations = [
        migrations.RunPython(rename_upload_mode, reverse_rename_upload_mode),
    ]
