// This file will be auto-generated by openapi-typescript
// Run: npm run generate

// Placeholder - will be replaced by generated types
export interface ApiSchema {
  // Auto-generated OpenAPI types will go here
}