# Generated by Django 4.2.23 on 2025-10-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='affected_frame_count',
            field=models.IntegerField(default=1, help_text='Number of frames where this issue was detected'),
        ),
        migrations.AddField(
            model_name='finding',
            name='average_confidence',
            field=models.FloatField(blank=True, help_text='Average AI confidence across all occurrences', null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='first_timestamp',
            field=models.FloatField(blank=True, help_text='Timestamp (seconds) when issue first appeared', null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='last_timestamp',
            field=models.FloatField(blank=True, help_text='Timestamp (seconds) when issue last appeared', null=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='confidence',
            field=models.FloatField(help_text='AI confidence score 0-1 (max when consolidated)'),
        ),
    ]
