# Generated by Django 4.2.23 on 2025-10-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_finding_affected_frame_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='estimated_minutes',
            field=models.IntegerField(blank=True, help_text='AI-estimated time in minutes to address this issue', null=True),
        ),
    ]
