# Generated by Django 4.2.24 on 2025-10-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_finding_estimated_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='category',
            field=models.CharField(choices=[('PPE', 'Personal Protective Equipment'), ('SAFETY', 'Safety'), ('CLEANLINESS', 'Cleanliness'), ('UNIFORM', 'Uniform Compliance'), ('MENU_BOARD', 'Menu Board'), ('FOOD_SAFETY', 'Food Safety & Hygiene'), ('EQUIPMENT', 'Equipment & Maintenance'), ('OPERATIONAL', 'Operational Compliance'), ('FOOD_QUALITY', 'Food Quality & Presentation'), ('STAFF_BEHAVIOR', 'Staff Behavior'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
