# Generated by Django 4.2.24 on 2025-10-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_alter_finding_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='equipment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='food_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='food_safety_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='operational_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='staff_behavior_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
