# Generated by Django 4.2.23 on 2025-10-02 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_inspection_data_from_video(apps, schema_editor):
    """Migrate inspection metadata from associated video"""
    Inspection = apps.get_model('inspections', 'Inspection')

    for inspection in Inspection.objects.select_related('video', 'video__store').all():
        if inspection.video:
            # Copy metadata from video to inspection
            inspection.title = inspection.video.title or f"Inspection {inspection.id}"
            inspection.created_by = inspection.video.uploaded_by
            inspection.store = inspection.video.store
            inspection.inspection_date = inspection.created_at
            inspection.save(update_fields=['title', 'created_by', 'store', 'inspection_date'])


def reverse_migrate_inspection_data(apps, schema_editor):
    """Reverse migration - no action needed as we're keeping video relationship temporarily"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0002_brand_is_trial_brand_trial_created_by'),
        ('inspections', '0005_inspection_equipment_score_and_more'),
    ]

    operations = [
        # Step 1: Add new fields (nullable)
        migrations.AddField(
            model_name='inspection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateTimeField(blank=True, help_text='When inspection was initiated', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='brands.store'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='title',
            field=models.CharField(default='', help_text='Inspection title', max_length=200),
        ),
        # Step 2: Migrate data from video to new fields
        migrations.RunPython(migrate_inspection_data_from_video, reverse_migrate_inspection_data),
        # Step 3: Remove old OneToOne relationship
        migrations.RemoveField(
            model_name='inspection',
            name='video',
        ),
    ]
