# Generated by Django 4.2.23 on 2025-10-02 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0006_migrate_to_multi_video_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finding',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this finding (for manual findings)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finding',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Manager confirmed this finding is correct'),
        ),
        migrations.AddField(
            model_name='finding',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True if manually added by manager, not AI-detected'),
        ),
        migrations.AddField(
            model_name='finding',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Manager dismissed this as false positive'),
        ),
        migrations.AddField(
            model_name='finding',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finding',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Why this finding was rejected'),
        ),
    ]
