# Generated by Django 4.2.24 on 2025-10-02 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0007_finding_approved_at_finding_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='assigned_inspector',
            field=models.ForeignKey(blank=True, help_text='Inspector assigned to review (enterprise mode only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_notes',
            field=models.TextField(blank=True, help_text='Detailed inspector notes and observations (enterprise mode)'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='report_generated_at',
            field=models.DateTimeField(blank=True, help_text='When report was generated', null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='report_url',
            field=models.CharField(blank=True, help_text='URL to generated PDF report (enterprise mode)', max_length=500),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='mode',
            field=models.CharField(choices=[('ENTERPRISE', 'Enterprise Mode'), ('COACHING', 'Coaching Mode')], max_length=20),
        ),
    ]
