# Generated by Django 4.2.24 on 2025-10-02 19:28

from django.db import migrations


def rename_inspection_mode(apps, schema_editor):
    """Rename INSPECTION mode to ENTERPRISE in existing data"""
    Inspection = apps.get_model('inspections', 'Inspection')
    Inspection.objects.filter(mode='INSPECTION').update(mode='ENTERPRISE')


def reverse_rename_inspection_mode(apps, schema_editor):
    """Reverse: rename ENTERPRISE back to INSPECTION"""
    Inspection = apps.get_model('inspections', 'Inspection')
    Inspection.objects.filter(mode='ENTERPRISE').update(mode='INSPECTION')


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_inspection_assigned_inspector_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_inspection_mode, reverse_rename_inspection_mode),
    ]
