# Generated by Django 4.2.24 on 2025-10-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_rename_inspection_to_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Why this finding was rejected'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector_notes',
            field=models.TextField(blank=True, default='', help_text='Detailed inspector notes and observations (enterprise mode)'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='report_url',
            field=models.CharField(blank=True, default='', help_text='URL to generated PDF report (enterprise mode)', max_length=500),
        ),
    ]
