# Generated by Django 4.2.24 on 2025-09-24 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Is this a trial brand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='trial_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_brands_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
