# Generated by Django 4.2.24 on 2025-10-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_is_trial_brand_trial_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='has_enterprise_access',
            field=models.BooleanField(default=False, help_text='Has access to inspector-led enterprise workflow'),
        ),
    ]
